services:
    db:
        image: postgres:latest
        volumes:
            - postgres_data:/var/lib/postgresql/data  # Container data
            - ./postgres_data:/var/lib/postgresql/data/external  # Host-accessible data
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5433:5433"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
            interval: 5s
            timeout: 5s
            retries: 5

    minicom_main_system:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PYTHONUNBUFFERED=1
            - DB_HOST=db
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        ports:
            - "8000:8000"
        volumes:
            - static_volume:/app/static
            - root_volume:/app
            - ../Documents/media:/app/media
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy

    nginx:
        build: ./nginx
        volumes:
            - static_volume:/app/static
            - root_volume:/app
            - ../Documents/media:/app/media
        ports:
            - "80:80"
        depends_on:
            - minicom_main_system

volumes:
    static_volume:
    root_volume:
    postgres_data: