# Generated by Django 5.1.6 on 2025-05-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ICBTRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_code", models.CharField(max_length=200)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("date_period", models.DateField()),
                ("month", models.CharField(max_length=20)),
                ("cross_point", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=30)),
                ("sex", models.CharField(max_length=30)),
                ("profession", models.CharField(max_length=60)),
                ("trader_residence", models.CharField(max_length=60)),
                ("product_origin", models.CharField(max_length=50)),
                ("product_destination", models.CharField(max_length=50)),
                ("transport_mode", models.CharField(max_length=50)),
                ("product", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=30)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "total_price_usd",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("latitude", models.DecimalField(decimal_places=10, max_digits=15)),
                ("longitude", models.DecimalField(decimal_places=10, max_digits=15)),
                ("accuracy", models.DecimalField(decimal_places=7, max_digits=12)),
            ],
            options={
                "db_table": "ICBTRecords",
                "indexes": [
                    models.Index(
                        fields=["start_time", "end_time", "date_period"],
                        name="ICBTRecords_start_t_814024_idx",
                    ),
                    models.Index(
                        fields=["cross_point"], name="ICBTRecords_cross_p_43cf6f_idx"
                    ),
                    models.Index(
                        fields=["product_origin", "product"],
                        name="ICBTRecords_product_37adec_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "form_code",
                            "start_time",
                            "end_time",
                            "date_period",
                            "month",
                            "cross_point",
                            "district",
                            "sex",
                            "profession",
                            "trader_residence",
                            "product_origin",
                            "product_destination",
                            "transport_mode",
                            "product",
                            "unit",
                            "quantity",
                            "unit_price",
                            "total_price",
                            "total_price_usd",
                        ),
                        name="icbt_unique_all_fields_combined",
                    )
                ],
            },
        ),
    ]
