# Generated by Django 5.1.6 on 2025-05-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="icbtrecord",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="icbtrecord",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
