# Generated by Django 5.1.6 on 2025-06-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0002_alter_icbtrecord_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="icbtrecord",
            name="month",
            field=models.CharField(max_length=20),
        ),
    ]
