# Generated by Django 5.1.6 on 2025-05-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0002_alter_icbtrecord_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="icbtrecord",
            name="form_code",
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name="icbtrecord",
            constraint=models.UniqueConstraint(
                fields=(
                    "form_code",
                    "start_time",
                    "end_time",
                    "date_period",
                    "month",
                    "cross_point",
                    "district",
                    "sex",
                    "profession",
                    "trader_residence",
                    "product_origin",
                    "product_destination",
                    "transport_mode",
                    "product",
                    "unit",
                    "quantity",
                    "unit_price",
                    "total_price",
                    "total_price_usd",
                ),
                name="icbt_unique_all_fields_combined",
            ),
        ),
    ]
