# Generated by Django 5.1.6 on 2025-06-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0003_alter_icbtrecord_month"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormalTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tin_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tax_payer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "rra_custom_office_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "rra_custom_office_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("rra_recorded_date", models.DateField()),
                ("month", models.CharField(blank=True, max_length=40, null=True)),
                ("regime", models.CharField(blank=True, max_length=30, null=True)),
                ("nbr_sad", models.IntegerField(blank=True, null=True)),
                ("item_nbr", models.IntegerField(blank=True, null=True)),
                ("hs_code", models.CharField(blank=True, max_length=20, null=True)),
                ("hs2_code", models.CharField(blank=True, max_length=10, null=True)),
                ("hs4_code", models.CharField(blank=True, max_length=14, null=True)),
                ("hs6_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "product_description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "local_product_description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "custom_border_post_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "custom_border_post_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "origin_country_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "origin_country_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "destination_country_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "destination_country_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "provenance_country_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "provenance_country_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stat_unit_rra",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "stat_unit_common",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "fob",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "freight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "insurance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "other_costs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cif",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "cif_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("IMPORT", "IMPORT"),
                            ("EXPORT", "EXPORT"),
                            ("RE-EXPORT", "RE-EXPORT"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "FormalTrade",
            },
        ),
        migrations.RemoveConstraint(
            model_name="icbtrecord",
            name="icbt_unique_all_fields_combined",
        ),
        migrations.RemoveIndex(
            model_name="icbtrecord",
            name="ICBTRecords_start_t_814024_idx",
        ),
        migrations.RemoveField(
            model_name="icbtrecord",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="icbtrecord",
            name="form_code",
        ),
        migrations.RemoveField(
            model_name="icbtrecord",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="icbtrecord",
            name="trader_residence",
        ),
        migrations.AddField(
            model_name="icbtrecord",
            name="age_range",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="icbtrecord",
            name="altitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="icbtrecord",
            name="cross_point_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="icbtrecord",
            name="date_period_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="icbtrecord",
            name="main_category",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="icbtrecord",
            name="product_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="icbtrecord",
            name="product_hscode",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="icbtrecord",
            name="sub_category",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="icbtrecord",
            name="trader_residence_country",
            field=models.CharField(default="", max_length=80),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="icbtrecord",
            index=models.Index(
                fields=["date_period"], name="ICBTRecords_date_pe_38061a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="icbtrecord",
            index=models.Index(
                fields=["date_period", "date_period_time"],
                name="ICBTRecords_date_pe_c00d54_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="icbtrecord",
            constraint=models.UniqueConstraint(
                fields=(
                    "date_period_time",
                    "date_period",
                    "month",
                    "cross_point",
                    "district",
                    "sex",
                    "profession",
                    "trader_residence_country",
                    "product_origin",
                    "product_destination",
                    "transport_mode",
                    "product",
                    "unit",
                    "quantity",
                    "unit_price",
                    "total_price",
                    "total_price_usd",
                ),
                name="icbt_unique_all_fields_combined",
            ),
        ),
        migrations.AddIndex(
            model_name="formaltrade",
            index=models.Index(
                fields=["tin_number"], name="FormalTrade_tin_num_5e2861_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formaltrade",
            index=models.Index(
                fields=["origin_country_name", "destination_country_name"],
                name="FormalTrade_origin__66a5db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="formaltrade",
            index=models.Index(
                fields=["rra_recorded_date"], name="FormalTrade_rra_rec_9ef87b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formaltrade",
            index=models.Index(fields=["month"], name="FormalTrade_month_36888f_idx"),
        ),
        migrations.AddConstraint(
            model_name="formaltrade",
            constraint=models.UniqueConstraint(
                fields=(
                    "tin_number",
                    "tax_payer_name",
                    "supplier_name",
                    "rra_custom_office_code",
                    "rra_recorded_date",
                    "regime",
                    "nbr_sad",
                    "item_nbr",
                    "hs_code",
                    "product_description",
                    "local_product_description",
                    "custom_border_post_code",
                    "origin_country_name",
                    "destination_country_name",
                    "provenance_country_name",
                    "stat_unit_rra",
                    "quantity",
                    "net_weight",
                    "fob",
                    "freight",
                    "insurance",
                    "other_costs",
                    "cif",
                    "cif_usd",
                    "category",
                ),
                name="formal_trade_unique_all_fields_combined",
            ),
        ),
    ]
