# Generated by Django 5.1.6 on 2025-07-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0004_formaltrade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formaltrade",
            name="fob_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
