# Generated by Django 5.1.6 on 2025-07-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0005_formaltrade_fob_usd"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="formaltrade",
            name="formal_trade_unique_all_fields_combined",
        ),
        migrations.AddConstraint(
            model_name="formaltrade",
            constraint=models.UniqueConstraint(
                fields=(
                    "tin_number",
                    "supplier_name",
                    "hs_code",
                    "rra_recorded_date",
                    "category",
                ),
                name="formal_trade_unique_all_fields_combined",
            ),
        ),
    ]
