# Generated by Django 5.1.6 on 2025-07-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trade",
            "0006_remove_formaltrade_formal_trade_unique_all_fields_combined_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="formaltrade",
            name="formal_trade_unique_all_fields_combined",
        ),
        migrations.AddConstraint(
            model_name="formaltrade",
            constraint=models.UniqueConstraint(
                fields=(
                    "tin_number",
                    "supplier_name",
                    "hs_code",
                    "rra_recorded_date",
                    "rra_custom_office_code",
                    "custom_border_post_code",
                    "fob",
                    "item_nbr",
                    "quantity",
                    "net_weight",
                    "category",
                ),
                name="formal_trade_unique_all_fields_combined",
            ),
        ),
    ]
