# Generated by Django 5.1.6 on 2025-07-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trade",
            "0007_remove_formaltrade_formal_trade_unique_all_fields_combined_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="formaltrade",
            name="formal_trade_unique_all_fields_combined",
        ),
        migrations.AddField(
            model_name="formaltrade",
            name="row_key",
            field=models.CharField(default="row_key", max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
