# Generated by Django 5.1.6 on 2025-07-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trade",
            "0008_remove_formaltrade_formal_trade_unique_all_fields_combined_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="formaltrade",
            name="row_key",
            field=models.TextField(unique=True),
        ),
    ]
