# Generated by Django 5.1.6 on 2025-07-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0009_alter_formaltrade_row_key"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="icbtrecord",
            name="icbt_unique_all_fields_combined",
        ),
        migrations.RemoveField(
            model_name="icbtrecord",
            name="product_code",
        ),
        migrations.AddField(
            model_name="icbtrecord",
            name="row_key",
            field=models.TextField(default="row_key", unique=True),
            preserve_default=False,
        ),
    ]
