# Generated by Django 5.1.6 on 2025-07-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0010_remove_icbtrecord_icbt_unique_all_fields_combined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="icbtrecord",
            name="age_range",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
