# Generated by Django 5.1.6 on 2025-07-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0011_alter_icbtrecord_age_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="icbtrecord",
            name="enumerator_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="icbtrecord",
            name="enumerator_name",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
