# Generated by Django 5.1.6 on 2025-07-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0012_icbtrecord_enumerator_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formaltrade",
            name="cif_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="formaltrade",
            name="fob",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="formaltrade",
            name="fob_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="formaltrade",
            name="freight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="formaltrade",
            name="insurance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="formaltrade",
            name="other_costs",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
    ]
