# Generated by Django 5.1.6 on 2025-05-29 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("industry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryProductReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "production_volume",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "current_installed_production",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("reported_on", models.DateTimeField(auto_now_add=True)),
                (
                    "justification_production_capacity",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "imported_raw_material_perc",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "production_local_sales_volume",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "production_export_volume",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "production_not_sold_yet_volume",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "production_disposed",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
            ],
            options={
                "db_table": "IndustryProductReports",
            },
        ),
        migrations.CreateModel(
            name="MonthsReportingPeriodConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("months", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "MonthsReportingPeriodConfigs",
            },
        ),
        migrations.CreateModel(
            name="ReportingPeriodPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="EmploymentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("current_male_permanent_employees", models.PositiveIntegerField()),
                ("current_male_casual_employees", models.PositiveIntegerField()),
                ("current_female_permanent_employees", models.PositiveIntegerField()),
                ("current_female_casual_employees", models.PositiveIntegerField()),
                ("new_male_permanent_employees", models.PositiveIntegerField()),
                ("new_male_casual_employees", models.PositiveIntegerField()),
                ("new_female_permanent_employees", models.PositiveIntegerField()),
                ("new_female_casual_employees", models.PositiveIntegerField()),
                ("job_loss", models.PositiveIntegerField()),
                ("current_male_youth_employees", models.PositiveIntegerField()),
                ("current_female_youth_employees", models.PositiveIntegerField()),
                ("improvement_suggestion", models.TextField(blank=True, null=True)),
                ("challenges_faced", models.TextField(blank=True, null=True)),
                ("support_needed", models.TextField(blank=True, null=True)),
                ("reported_on", models.DateTimeField(auto_now_add=True)),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="industry.companysite",
                    ),
                ),
            ],
            options={
                "db_table": "EmploymentReports",
            },
        ),
    ]
