# Generated by Django 5.1.6 on 2025-05-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllocatedPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_plot_upi",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "upi_status",
                    models.CharField(
                        choices=[
                            ("Not Yet Requested", "Not Requested"),
                            (
                                "Pending To Land Institution",
                                "Pending To Land Institution",
                            ),
                            ("Issued", "Issued"),
                        ],
                        default="Not Yet Requested",
                        max_length=30,
                    ),
                ),
                (
                    "plot_size",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=13, null=True
                    ),
                ),
                ("is_in_park", models.BooleanField(default=True)),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
                ("is_land_title_issued", models.BooleanField(default=False)),
                (
                    "land_title_status",
                    models.CharField(
                        choices=[
                            ("Issued", "Issued"),
                            ("Not Yet Requested", "Not Yet Requested"),
                            ("Pending", "Pending"),
                        ],
                        default="Not Yet Requested",
                        max_length=20,
                    ),
                ),
                (
                    "date_of_letter_addressed_to_nla",
                    models.DateField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "AllocatedPlots",
            },
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("tin_number", models.PositiveIntegerField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("INDUSTRY", "INDUSTRY"),
                            ("NOT INDUSTRY", "NOT INDUSTRY"),
                        ],
                        max_length=30,
                    ),
                ),
                ("phone_contact", models.CharField(max_length=20)),
                ("email_contact", models.EmailField(max_length=200)),
                ("registeration_date", models.DateField(blank=True, null=True)),
                ("investor_origin_country", models.TextField()),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("Large", "Large"),
                            ("Medium", "Medium"),
                            ("Small", "Small"),
                            ("Micro", "Micro"),
                        ],
                        max_length=15,
                    ),
                ),
                ("profile_created_date", models.DateTimeField(auto_now_add=True)),
                ("managing_director_name", models.CharField(max_length=200)),
                (
                    "managing_director_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("headquaters_province", models.CharField(max_length=60)),
                ("headquaters_district", models.CharField(max_length=60)),
                ("headquaters_sector", models.CharField(max_length=60)),
                ("headquaters_cell", models.CharField(max_length=60)),
                ("headquaters_village", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "CompanyProfiles",
            },
        ),
        migrations.CreateModel(
            name="CompanySite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "benefited_electricity_tarrif",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=12, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=12, null=True
                    ),
                ),
                ("province", models.CharField(max_length=60)),
                ("district", models.CharField(max_length=60)),
                ("sector", models.CharField(max_length=60)),
                ("cell", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "construction_status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("Under Construction", "Under Construction"),
                            ("Completed", "Completed"),
                            ("Stopped", "Stopped"),
                        ],
                        default="Not Started",
                        max_length=20,
                    ),
                ),
                (
                    "operational_status",
                    models.CharField(
                        choices=[
                            ("Not Operational", "Not Operational"),
                            ("Partially Operational", "Partially Operational"),
                            ("Fully Operational", "Fully Operational"),
                        ],
                        default="Not Operational",
                        max_length=30,
                    ),
                ),
                ("construction_start_date", models.DateField(blank=True, null=True)),
                ("operational_start_date", models.DateField(blank=True, null=True)),
                ("is_in_park", models.BooleanField(default=True)),
                (
                    "occupied_space",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=13, null=True
                    ),
                ),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
                (
                    "investment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "investment_currency",
                    models.CharField(
                        blank=True,
                        choices=[("USD", "USD"), ("RWF", "RWF")],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "CompanySites",
            },
        ),
        migrations.CreateModel(
            name="ContractPaymentInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expected_payment_date", models.DateField()),
                ("actual_payment_date", models.DateField(blank=True, null=True)),
                (
                    "expected_payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=13),
                ),
                (
                    "actual_paid_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=13, null=True
                    ),
                ),
                (
                    "accrued_penalties",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=13,
                        null=True,
                    ),
                ),
                (
                    "paid_penalties",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=13,
                        null=True,
                    ),
                ),
                (
                    "amount_overdued",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=13,
                        null=True,
                    ),
                ),
                (
                    "days_in_arrears",
                    models.PositiveBigIntegerField(
                        blank=True, default=0, editable=False, null=True
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("FULLY PAID", "FULLY PAID"),
                            ("PARTIALLY PAID", "PARTIALLY PAID"),
                            ("NOT PAID", "NOT PAID"),
                        ],
                        default="NOT PAID",
                        max_length=30,
                    ),
                ),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ContractPaymentInstallments",
            },
        ),
        migrations.CreateModel(
            name="IndustryAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Main Document", "Main Document"),
                            ("Other Supporting Document", "Other Supporting Document"),
                        ],
                        max_length=40,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=200, null=True)),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                ("document", models.FileField(upload_to="Industry_attachments/")),
                ("document_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "IndustryAttachments",
            },
        ),
        migrations.CreateModel(
            name="IndustryContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signing_date", models.DateField(blank=True, null=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[("INITIAL", "INITIAL"), ("AMENDMENT", "AMENDMENT")],
                        max_length=35,
                    ),
                ),
                (
                    "contract_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=13, null=True
                    ),
                ),
                (
                    "contract_currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("RWF", "RWF")], max_length=10
                    ),
                ),
                (
                    "operational_years",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "contract_document",
                    models.FileField(
                        blank=True, null=True, upload_to="Contract_documents/contracts/"
                    ),
                ),
                ("contract_document_url", models.URLField(blank=True, null=True)),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
                ("closure_comment", models.TextField(blank=True, null=True)),
                ("is_contract_closed", models.BooleanField(default=False)),
                (
                    "irembo_application_number",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
            ],
            options={
                "db_table": "IndustryContracts",
            },
        ),
        migrations.CreateModel(
            name="IndustryContractPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_amount_to_pay",
                    models.DecimalField(decimal_places=2, max_digits=13),
                ),
                (
                    "payment_currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("RWF", "RWF")], max_length=6
                    ),
                ),
                (
                    "payment_modality",
                    models.CharField(
                        choices=[
                            ("SINGLE FULL PAYMENT", "SINGLE FULL PAYMENT"),
                            ("INSTALLMENTS", "INSTALLMENTS"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        default="NO PAYMENT MADE", editable=False, max_length=40
                    ),
                ),
                ("number_of_installments", models.PositiveBigIntegerField()),
                (
                    "total_amount_paid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=13,
                        null=True,
                    ),
                ),
                (
                    "total_amount_unpaid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=13,
                        null=True,
                    ),
                ),
                (
                    "accrued_penalties",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=13,
                        null=True,
                    ),
                ),
                (
                    "paid_penalties",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=13,
                        null=True,
                    ),
                ),
                (
                    "amount_overdued",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=13,
                        null=True,
                    ),
                ),
                (
                    "days_in_arrears",
                    models.PositiveBigIntegerField(
                        blank=True, default=0, editable=False, null=True
                    ),
                ),
                ("next_payment_date", models.DateField(blank=True, null=True)),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction_to_refund",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "irembo_application_number",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
            ],
            options={
                "db_table": "IndustryContractPayments",
            },
        ),
        migrations.CreateModel(
            name="IndustryEconomicSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "IndustryEconomicSectors",
            },
        ),
        migrations.CreateModel(
            name="IndustryEconomicZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Special Economic Zone", "Special Economic Zone"),
                            ("Industrial Park", "Industrial Park"),
                            ("Light Industrial Zone", "Light Industrial Zone"),
                        ],
                        max_length=60,
                    ),
                ),
                (
                    "total_land_size",
                    models.DecimalField(decimal_places=5, max_digits=13),
                ),
                ("leasable_land", models.DecimalField(decimal_places=5, max_digits=13)),
                ("province", models.CharField(max_length=60)),
                ("district", models.CharField(max_length=60)),
                ("sector", models.CharField(max_length=60)),
                ("cell", models.CharField(blank=True, max_length=60, null=True)),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
                (
                    "park_plots_map",
                    models.FileField(
                        blank=True, null=True, upload_to="Industrial_parks_plots_maps/"
                    ),
                ),
            ],
            options={
                "db_table": "IndustryEconomicZones",
            },
        ),
        migrations.CreateModel(
            name="IndustryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_brand_name", models.CharField(max_length=200)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "quantity_measure",
                    models.CharField(
                        choices=[
                            ("Volume", "Volume"),
                            ("Weight", "Weight"),
                            ("Size", "Size"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_measure_unit",
                    models.CharField(
                        choices=[
                            ("mL", "Milliliters"),
                            ("g", "Grams"),
                            ("m", "meters"),
                            ("unk", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "packaging_material",
                    models.CharField(
                        choices=[
                            ("Paper", "Paper"),
                            ("Cardboard", "Cardboard"),
                            ("Glass", "Glass"),
                            ("Plastic", "Plastic"),
                            ("Cotton", "Cotton"),
                            ("Aluminum", "Aluminum"),
                            ("Plant based", "Plant based"),
                            ("Metal", "Metal"),
                            ("Wood", "Wood"),
                            ("Other", "Other"),
                        ],
                        max_length=60,
                    ),
                ),
                (
                    "production_installed_capacity",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "production_installed_capacity_unit",
                    models.CharField(
                        choices=[
                            ("Pieces", "Pieces"),
                            ("Liters", "Liters"),
                            ("Kilograms", "Kilograms"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "production_installed_capacity_period",
                    models.CharField(
                        choices=[("Day", "Day"), ("Month", "Month"), ("Year", "Year")],
                        max_length=20,
                    ),
                ),
                (
                    "production_line_tech",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "IndustryProducts",
            },
        ),
        migrations.CreateModel(
            name="LandRequestInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_date", models.DateField(blank=True, null=True)),
                ("request_closure_date", models.DateField(blank=True, null=True)),
                (
                    "requested_land_size",
                    models.DecimalField(decimal_places=5, max_digits=13),
                ),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
                (
                    "irembo_application_number",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
            ],
            options={
                "db_table": "LandRequestInformations",
            },
        ),
        migrations.CreateModel(
            name="PartitionedPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plot_number", models.CharField(max_length=30)),
                (
                    "partitioned_plot_upi",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "upi_status",
                    models.CharField(
                        choices=[
                            ("Not Yet Requested", "Not Requested"),
                            (
                                "Pending To Land Institution",
                                "Pending To Land Institution",
                            ),
                            ("Issued", "Issued"),
                        ],
                        max_length=30,
                    ),
                ),
                ("plot_size", models.DecimalField(decimal_places=5, max_digits=13)),
                ("is_allocated", models.BooleanField(default=False)),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "PartitionedPlots",
            },
        ),
        migrations.CreateModel(
            name="PaymentInstallmentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=13),
                ),
                (
                    "payment_proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Contract_documents/payment_proofs/",
                    ),
                ),
                ("payment_proof_url", models.URLField(blank=True, null=True)),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=13,
                        null=True,
                    ),
                ),
                ("is_refunded", models.BooleanField(default=False)),
                ("refunded_date", models.DateField(blank=True, null=True)),
                (
                    "refund_proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Contract_documents/refund_payment_proofs/",
                    ),
                ),
                ("refund_proof_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "PaymentInstallmentTransactions",
            },
        ),
    ]
