# Generated by Django 5.1.6 on 2025-06-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partitionedplot",
            name="coordinates",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
