# Generated by Django 5.1.6 on 2025-06-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0003_partitionedplot_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="managing_director_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
