# Generated by Django 5.1.6 on 2025-06-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0004_alter_companyprofile_managing_director_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Large", "Large"),
                    ("Medium", "Medium"),
                    ("Small", "Small"),
                    ("Micro", "Micro"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="headquaters_cell",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="headquaters_district",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="headquaters_province",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="headquaters_sector",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="headquaters_village",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="investor_origin_country",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="phone_contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
