# Generated by Django 5.1.6 on 2025-06-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkuploadjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
