# Generated by Django 5.1.6 on 2025-06-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_alter_bulkuploadjob_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BNRUSDAveragePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=30)),
                ("year", models.IntegerField()),
                ("rate", models.DecimalField(decimal_places=6, max_digits=12)),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "BNRUSDAveragePrices",
            },
        ),
        migrations.CreateModel(
            name="ProductMeasurements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_abbr", models.CharField(max_length=5)),
                ("long_abbr", models.CharField(max_length=10)),
                ("full_form", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ProductMeasurements",
            },
        ),
        migrations.CreateModel(
            name="RRACustomCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("custom_name", models.CharField(max_length=100)),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "RRACustomCodes",
            },
        ),
        migrations.CreateModel(
            name="WorldCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=6)),
                ("country_name", models.CharField(max_length=100)),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "WorldCountries",
            },
        ),
        migrations.AddField(
            model_name="bulkuploadjob",
            name="global_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bulkuploadjob",
            name="processed_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
