# Generated by Django 5.1.6 on 2025-07-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "automation",
            "0004_bnrusdaverageprice_productmeasurements_rracustomcode_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmeasurements",
            name="short_abbr",
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name="rracustomcode",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="worldcountry",
            name="country_code",
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AddConstraint(
            model_name="bnrusdaverageprice",
            constraint=models.UniqueConstraint(
                fields=("month", "year"), name="USDRateUniqueConstraint"
            ),
        ),
    ]
