# Generated by Django 5.1.6 on 2025-07-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0005_alter_productmeasurements_short_abbr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkuploadjob",
            name="processed_count",
            field=models.IntegerField(default=0),
        ),
    ]
