# Generated by Django 5.1.6 on 2025-07-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0006_alter_bulkuploadjob_processed_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkuploadjob",
            name="processing_minutes",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
